# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java
trigger:
- master
pool:
  vmImage: 'ubuntu-latest'
stages:
- stage: CI
  jobs:
  - job: Build
    steps:
    - task: ServiceNow-DevOps-Agent-Job-Notification@2
      inputs:
        connectedServiceName: 'Servicenow IDC 2 creds'
        Phase: 'STARTED'
    - task: Maven@3
      inputs:
        mavenPomFile: 'pom.xml'
        mavenOptions: '-Xmx3072m'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '1.8'
        jdkArchitectureOption: 'x64'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        goals: 'package'
    - publish: $(System.DefaultWorkingDirectory)/target/globex-web.war
      artifact: Globex-web
    - task: ServiceNow-DevOps-Artifact-Registration@16
      inputs:
        connectedServiceName: 'Servicenow IDC 2 creds'
        artifactsPayload: |
          {
          "artifacts":[
          {
          "name":"test.jar",
          "version":"1.$(Build.BuildId)",
          "semanticVersion":"1.$(Build.BuildId).0",
          "repositoryName":"Test"
          }
          ]
          }
    - task: ServiceNow-DevOps-Agent-Job-Notification@2
      inputs:
        connectedServiceName: 'Servicenow IDC 2 creds'
        Phase: 'COMPLETED'
- stage: UAT_deploy
  jobs:
  - deployment: DeployUAT
    displayName: UAT
    pool:
      vmImage: 'Ubuntu-16.04'
    environment: 'UAT'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: ServiceNow-DevOps-Agent-Job-Notification@2
            inputs:
              connectedServiceName: 'Servicenow IDC 2 creds'
              upstream: 'Build'
              Phase: 'STARTED'
          - script: echo my first deployment
          - task: ServiceNow-DevOps-Agent-Job-Notification@2
            inputs:
              connectedServiceName: 'Servicenow IDC 2 creds'
              upstream: 'Build'
              Phase: 'COMPLETED'
- stage: UAT_test
  jobs:
  - deployment: DeployUAT
    displayName: UAT Test
    pool:
      vmImage: 'Ubuntu-16.04'
    environment: 'UAT'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: ServiceNow-DevOps-Agent-Job-Notification@2
            inputs:
              connectedServiceName: 'Servicenow IDC 2 creds'
              upstream: 'UAT'
              Phase: 'STARTED'
          - script: echo my first deployment
          - task: ServiceNow-DevOps-Agent-Job-Notification@2
            inputs:
              connectedServiceName: 'Servicenow IDC 2 creds'
              upstream: 'UAT'
              Phase: 'COMPLETED'