# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java
trigger:
- master
pool:
  vmImage: 'ubuntu-latest'
stages:
- stage: CI
  jobs:
  - job: Build
    steps:
    - task: Maven@3
      inputs:
        mavenPomFile: 'pom.xml'
        mavenOptions: '-Xmx3072m'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '1.8'
        jdkArchitectureOption: 'x64'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        goals: 'package'
    - publish: $(System.DefaultWorkingDirectory)/target/globex-web.war
      artifact: Globex-web
- stage: UAT_deploy
  jobs:
  - deployment: DeployUAT
    displayName: UAT
    pool:
      vmImage: 'Ubuntu-16.04'
    environment: 'UAT'
- stage: UAT_test
  jobs:
  - deployment: DeployUAT
    displayName: UAT Test
    pool:
      vmImage: 'Ubuntu-16.04'
    environment: 'UAT'